plugins:
  - jekyll-seo-tag
github: [metadata]
repository: mehmetseckin/mehmetseckin.github.io
title: Mehmet Seckin
description: My personal website and blog.
social:
  name: Mehmet Seckin
  links:
    - https://github.com/mehmetseckin/
    - https://linkedin.com/in/mehmet-seckin/
