plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

url: "https://www.mehmetseckin.com"
github: [metadata]
repository: mehmetseckin/mehmetseckin.github.io
title: Mehmet Seckin
description: My personal website and blog
social:
  name: Mehmet Seckin
  links:
    - https://github.com/mehmetseckin/
    - https://linkedin.com/in/mehmet-seckin/

author:
  name: Mehmet Seckin
  email: mehmet@seckin.me

emptyArray: []

collections:
  .well-known:
    output: true

defaults:
  - scope:
      path: '_posts'
      type: posts
    values:
      layout: post
      author: mehmetseckin
      commenting: open

authors:
  mehmetseckin:
    name: Mehmet Seckin
    email: mehmet@seckin.me
    url: https://www.mehmetseckin.com

theme: jekyll-theme-minimal
